/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sistemaestacionamiento.gui;

/**
 *
 * @author USER
 */
public class CE_RegistrarIngreso extends javax.swing.JPanel {

    /**
     * Creates new form IngresarAuto
     */
    public CE_RegistrarIngreso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipovehiculo_title = new javax.swing.JLabel();
        Nplaca_title = new javax.swing.JLabel();
        Nplaca_txt = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        registraringreso_button = new javax.swing.JButton();
        restablecer_button = new javax.swing.JButton();
        registraringreso_title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        aviso_tipovehiculo = new javax.swing.JLabel();
        aviso_Nplaca = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        encolado_title = new javax.swing.JLabel();
        horaingreso_title = new javax.swing.JLabel();
        encoladoposicion_txt = new javax.swing.JLabel();
        horaingreso_txt = new javax.swing.JLabel();
        espacioasignado_title = new javax.swing.JLabel();
        espacioasignado_txt = new javax.swing.JLabel();
        hayespaciodisponible_txt = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tipovehiculo_title.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        tipovehiculo_title.setForeground(new java.awt.Color(102, 102, 102));
        tipovehiculo_title.setText("Tipo de vehículo:");
        add(tipovehiculo_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        Nplaca_title.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        Nplaca_title.setForeground(new java.awt.Color(102, 102, 102));
        Nplaca_title.setText("N° Placa:");
        add(Nplaca_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        Nplaca_txt.setBackground(new java.awt.Color(204, 204, 204));
        Nplaca_txt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Nplaca_txt.setForeground(new java.awt.Color(102, 102, 102));
        Nplaca_txt.setBorder(null);
        Nplaca_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nplaca_txtActionPerformed(evt);
            }
        });
        add(Nplaca_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 110, 20));

        jComboBox1.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auto", "Camión", "Camioneta", "Motocicleta" }));
        jComboBox1.setBorder(null);
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 110, -1));

        registraringreso_button.setBackground(new java.awt.Color(31, 39, 115));
        registraringreso_button.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        registraringreso_button.setForeground(new java.awt.Color(225, 225, 225));
        registraringreso_button.setText("Registrar Ingreso");
        registraringreso_button.setBorder(null);
        registraringreso_button.setBorderPainted(false);
        add(registraringreso_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 130, 30));

        restablecer_button.setBackground(new java.awt.Color(82, 82, 82));
        restablecer_button.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        restablecer_button.setForeground(new java.awt.Color(225, 225, 225));
        restablecer_button.setText("Restablecer");
        restablecer_button.setBorder(null);
        add(restablecer_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 110, 20));

        registraringreso_title.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        registraringreso_title.setForeground(new java.awt.Color(58, 65, 133));
        registraringreso_title.setText("Registro de Ingreso de Vehículo");
        add(registraringreso_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 250, 20));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 102));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 153));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 240, 10));

        aviso_tipovehiculo.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        aviso_tipovehiculo.setForeground(new java.awt.Color(255, 102, 102));
        add(aviso_tipovehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 170, 20));

        aviso_Nplaca.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        aviso_Nplaca.setForeground(new java.awt.Color(255, 102, 102));
        add(aviso_Nplaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 170, 20));

        jPanel1.setBackground(new java.awt.Color(36, 36, 36));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        encolado_title.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        encolado_title.setForeground(new java.awt.Color(225, 225, 225));
        encolado_title.setText("Encolado en Posición:");
        jPanel1.add(encolado_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 140, 20));

        horaingreso_title.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        horaingreso_title.setForeground(new java.awt.Color(225, 225, 225));
        horaingreso_title.setText("Hora de Ingreso:");
        jPanel1.add(horaingreso_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 110, 20));

        encoladoposicion_txt.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        encoladoposicion_txt.setForeground(new java.awt.Color(225, 225, 225));
        jPanel1.add(encoladoposicion_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 80, 20));

        horaingreso_txt.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        horaingreso_txt.setForeground(new java.awt.Color(225, 225, 225));
        jPanel1.add(horaingreso_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 60, 20));

        espacioasignado_title.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        espacioasignado_title.setForeground(new java.awt.Color(225, 225, 225));
        espacioasignado_title.setText("Espacio Asignado:");
        jPanel1.add(espacioasignado_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 20));

        espacioasignado_txt.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        espacioasignado_txt.setForeground(new java.awt.Color(225, 225, 225));
        jPanel1.add(espacioasignado_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 80, 20));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 460, 90));

        hayespaciodisponible_txt.setForeground(new java.awt.Color(51, 51, 51));
        add(hayespaciodisponible_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 170, 30));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 110, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 110, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void Nplaca_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nplaca_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nplaca_txtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nplaca_title;
    private javax.swing.JTextField Nplaca_txt;
    private javax.swing.JLabel aviso_Nplaca;
    private javax.swing.JLabel aviso_tipovehiculo;
    private javax.swing.JLabel encolado_title;
    private javax.swing.JLabel encoladoposicion_txt;
    private javax.swing.JLabel espacioasignado_title;
    private javax.swing.JLabel espacioasignado_txt;
    private javax.swing.JLabel hayespaciodisponible_txt;
    private javax.swing.JLabel horaingreso_title;
    private javax.swing.JLabel horaingreso_txt;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton registraringreso_button;
    private javax.swing.JLabel registraringreso_title;
    private javax.swing.JButton restablecer_button;
    private javax.swing.JLabel tipovehiculo_title;
    // End of variables declaration//GEN-END:variables
}
