/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sistemaestacionamiento.gui;

/**
 *
 * @author USER
 */
public class CE_RegistrarSalida extends javax.swing.JPanel {

    /**
     * Creates new form CE_RegistrarSalida
     */
    public CE_RegistrarSalida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrarsalida_title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Nplaca_txt = new javax.swing.JTextField();
        registrarsalida_button = new javax.swing.JButton();
        restablecer_button = new javax.swing.JButton();
        Nplaca_title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        espacio_title = new javax.swing.JLabel();
        espacio_txt = new javax.swing.JLabel();
        tipovehiculo_title = new javax.swing.JLabel();
        horaingreso_title = new javax.swing.JLabel();
        tipovehiculo_txt = new javax.swing.JLabel();
        horaingreso_txt = new javax.swing.JLabel();
        datosingreso_title = new javax.swing.JLabel();
        buscarvehiculo_button = new javax.swing.JButton();
        tarifatotal_title = new javax.swing.JLabel();
        tarifatotal_txt = new javax.swing.JLabel();
        aviso_busqueda = new javax.swing.JLabel();
        estadosalida_txt = new javax.swing.JLabel();
        tiempototal_title = new javax.swing.JLabel();
        tiempototal_txt = new javax.swing.JLabel();
        tarifaporhora_title1 = new javax.swing.JLabel();
        tarifaporhora_txt1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrarsalida_title.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        registrarsalida_title.setForeground(new java.awt.Color(58, 65, 133));
        registrarsalida_title.setText("Registro de Salida de Vehículo");
        add(registrarsalida_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 250, 20));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 102));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 153));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 240, 10));

        Nplaca_txt.setBackground(new java.awt.Color(204, 204, 204));
        Nplaca_txt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Nplaca_txt.setForeground(new java.awt.Color(102, 102, 102));
        Nplaca_txt.setBorder(null);
        Nplaca_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nplaca_txtActionPerformed(evt);
            }
        });
        add(Nplaca_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 110, 20));

        registrarsalida_button.setBackground(new java.awt.Color(31, 39, 115));
        registrarsalida_button.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        registrarsalida_button.setForeground(new java.awt.Color(225, 225, 225));
        registrarsalida_button.setText("Registrar Salida");
        registrarsalida_button.setBorder(null);
        registrarsalida_button.setBorderPainted(false);
        add(registrarsalida_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 130, 30));

        restablecer_button.setBackground(new java.awt.Color(82, 82, 82));
        restablecer_button.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        restablecer_button.setForeground(new java.awt.Color(225, 225, 225));
        restablecer_button.setText("Restablecer");
        restablecer_button.setBorder(null);
        add(restablecer_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 110, 20));

        Nplaca_title.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        Nplaca_title.setForeground(new java.awt.Color(102, 102, 102));
        Nplaca_title.setText("N° Placa:");
        add(Nplaca_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jPanel1.setBackground(new java.awt.Color(36, 36, 36));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        espacio_title.setBackground(new java.awt.Color(204, 204, 204));
        espacio_title.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        espacio_title.setForeground(new java.awt.Color(225, 225, 225));
        espacio_title.setText("Espacio:");
        jPanel1.add(espacio_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 110, 30));

        espacio_txt.setBackground(new java.awt.Color(204, 204, 204));
        espacio_txt.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        espacio_txt.setForeground(new java.awt.Color(225, 225, 225));
        jPanel1.add(espacio_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 110, 30));

        tipovehiculo_title.setBackground(new java.awt.Color(204, 204, 204));
        tipovehiculo_title.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        tipovehiculo_title.setForeground(new java.awt.Color(225, 225, 225));
        tipovehiculo_title.setText("Tipo de Vehículo:");
        jPanel1.add(tipovehiculo_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, 30));

        horaingreso_title.setBackground(new java.awt.Color(204, 204, 204));
        horaingreso_title.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        horaingreso_title.setForeground(new java.awt.Color(225, 225, 225));
        horaingreso_title.setText("Hora de ingreso:   ");
        jPanel1.add(horaingreso_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 30));

        tipovehiculo_txt.setBackground(new java.awt.Color(204, 204, 204));
        tipovehiculo_txt.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        tipovehiculo_txt.setForeground(new java.awt.Color(225, 225, 225));
        jPanel1.add(tipovehiculo_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 110, 30));

        horaingreso_txt.setBackground(new java.awt.Color(204, 204, 204));
        horaingreso_txt.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        horaingreso_txt.setForeground(new java.awt.Color(225, 225, 225));
        jPanel1.add(horaingreso_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 110, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 260, 120));

        datosingreso_title.setBackground(new java.awt.Color(51, 51, 51));
        datosingreso_title.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        datosingreso_title.setForeground(new java.awt.Color(51, 51, 51));
        datosingreso_title.setText("Datos de Ingreso:");
        add(datosingreso_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 110, -1));

        buscarvehiculo_button.setBackground(new java.awt.Color(31, 39, 115));
        buscarvehiculo_button.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        buscarvehiculo_button.setForeground(new java.awt.Color(225, 225, 225));
        buscarvehiculo_button.setText("Buscar Vehículo");
        buscarvehiculo_button.setBorder(null);
        buscarvehiculo_button.setBorderPainted(false);
        add(buscarvehiculo_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 130, 30));

        tarifatotal_title.setBackground(new java.awt.Color(51, 51, 51));
        tarifatotal_title.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        tarifatotal_title.setForeground(new java.awt.Color(51, 51, 51));
        tarifatotal_title.setText("Tarifa Total:");
        add(tarifatotal_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 70, 30));

        tarifatotal_txt.setBackground(new java.awt.Color(204, 204, 204));
        tarifatotal_txt.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        tarifatotal_txt.setForeground(new java.awt.Color(51, 51, 51));
        add(tarifatotal_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 70, 30));

        aviso_busqueda.setBackground(new java.awt.Color(51, 51, 51));
        aviso_busqueda.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        aviso_busqueda.setForeground(new java.awt.Color(255, 102, 102));
        add(aviso_busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 160, 30));

        estadosalida_txt.setForeground(new java.awt.Color(51, 51, 51));
        add(estadosalida_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 150, 20));

        tiempototal_title.setBackground(new java.awt.Color(51, 51, 51));
        tiempototal_title.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        tiempototal_title.setForeground(new java.awt.Color(51, 51, 51));
        tiempototal_title.setText("Tiempo Total:");
        add(tiempototal_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 90, 30));

        tiempototal_txt.setBackground(new java.awt.Color(204, 204, 204));
        tiempototal_txt.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        tiempototal_txt.setForeground(new java.awt.Color(51, 51, 51));
        add(tiempototal_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 70, 30));

        tarifaporhora_title1.setBackground(new java.awt.Color(51, 51, 51));
        tarifaporhora_title1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        tarifaporhora_title1.setForeground(new java.awt.Color(51, 51, 51));
        tarifaporhora_title1.setText("Tarifa x Hora:");
        add(tarifaporhora_title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 90, 30));

        tarifaporhora_txt1.setBackground(new java.awt.Color(204, 204, 204));
        tarifaporhora_txt1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        tarifaporhora_txt1.setForeground(new java.awt.Color(0, 0, 102));
        tarifaporhora_txt1.setText("...");
        add(tarifaporhora_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 70, 30));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 110, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void Nplaca_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nplaca_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nplaca_txtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nplaca_title;
    private javax.swing.JTextField Nplaca_txt;
    private javax.swing.JLabel aviso_busqueda;
    private javax.swing.JButton buscarvehiculo_button;
    private javax.swing.JLabel datosingreso_title;
    private javax.swing.JLabel espacio_title;
    private javax.swing.JLabel espacio_txt;
    private javax.swing.JLabel estadosalida_txt;
    private javax.swing.JLabel horaingreso_title;
    private javax.swing.JLabel horaingreso_txt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton registrarsalida_button;
    private javax.swing.JLabel registrarsalida_title;
    private javax.swing.JButton restablecer_button;
    private javax.swing.JLabel tarifaporhora_title1;
    private javax.swing.JLabel tarifaporhora_txt1;
    private javax.swing.JLabel tarifatotal_title;
    private javax.swing.JLabel tarifatotal_txt;
    private javax.swing.JLabel tiempototal_title;
    private javax.swing.JLabel tiempototal_txt;
    private javax.swing.JLabel tipovehiculo_title;
    private javax.swing.JLabel tipovehiculo_txt;
    // End of variables declaration//GEN-END:variables
}
