/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemaestacionamiento.gui;

import java.awt.Image;
import java.net.URL;
import javax.swing.*;
import java.awt.*;


/**
 *
 * @author USER
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
        
        SetImageLabel(login_icon, "imagenes/login_icon.png");
        SetImageLabel(ingresar_button, "imagenes/ingresar_button_default.png");
        SetImageLabel(login_fondo, "imagenes/login_fondo.png");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        login_title = new javax.swing.JLabel();
        usuario_title = new javax.swing.JLabel();
        contrasena_title = new javax.swing.JLabel();
        usuario_txt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        contrasena_txt = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        login_icon = new javax.swing.JLabel();
        ingresar_button = new javax.swing.JLabel();
        mostrarcontrasena_checkbox = new javax.swing.JCheckBox();
        aviso_contrasena = new javax.swing.JLabel();
        aviso_usuario = new javax.swing.JLabel();
        login_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login_title.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        login_title.setForeground(new java.awt.Color(40, 40, 146));
        login_title.setText("Log In");
        jPanel2.add(login_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 121, 70, 30));

        usuario_title.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        usuario_title.setForeground(new java.awt.Color(95, 95, 158));
        usuario_title.setText("Usuario:");
        jPanel2.add(usuario_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        contrasena_title.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        contrasena_title.setForeground(new java.awt.Color(95, 95, 158));
        contrasena_title.setText("Contraseña:");
        jPanel2.add(contrasena_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        usuario_txt.setBackground(new java.awt.Color(255, 255, 255));
        usuario_txt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        usuario_txt.setText("Ingrese su nombre de usuario");
        usuario_txt.setBorder(null);
        usuario_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usuario_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usuario_txtFocusLost(evt);
            }
        });
        jPanel2.add(usuario_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 200, 40));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 200, 10));

        contrasena_txt.setBackground(new java.awt.Color(255, 255, 255));
        contrasena_txt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        contrasena_txt.setText("••••••••••••");
        contrasena_txt.setBorder(null);
        contrasena_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contrasena_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                contrasena_txtFocusLost(evt);
            }
        });
        contrasena_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasena_txtActionPerformed(evt);
            }
        });
        jPanel2.add(contrasena_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 200, 40));

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 200, 10));

        login_icon.setText("jLabel1");
        jPanel2.add(login_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 80, 80));

        ingresar_button.setText("jLabel1");
        ingresar_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresar_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ingresar_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ingresar_buttonMouseExited(evt);
            }
        });
        jPanel2.add(ingresar_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 120, 40));

        mostrarcontrasena_checkbox.setBackground(new java.awt.Color(255, 255, 255));
        mostrarcontrasena_checkbox.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mostrarcontrasena_checkbox.setText("        Mostrar contraseña");
        mostrarcontrasena_checkbox.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/checkbutton_default_icon.png"))); // NOI18N
        mostrarcontrasena_checkbox.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/checkbutton_active_icon.png"))); // NOI18N
        mostrarcontrasena_checkbox.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/checkbutton_active_icon.png"))); // NOI18N
        mostrarcontrasena_checkbox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mostrarcontrasena_checkboxStateChanged(evt);
            }
        });
        jPanel2.add(mostrarcontrasena_checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        aviso_contrasena.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        aviso_contrasena.setForeground(new java.awt.Color(255, 102, 102));
        jPanel2.add(aviso_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 200, 20));

        aviso_usuario.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        aviso_usuario.setForeground(new java.awt.Color(255, 102, 102));
        jPanel2.add(aviso_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 200, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 280, 490));

        login_fondo.setText("jLabel1");
        jPanel1.add(login_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contrasena_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasena_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasena_txtActionPerformed

    private void usuario_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuario_txtFocusGained
        if(this.usuario_txt.getText().equals("Ingrese su nombre de usuario")){
            this.usuario_txt.setText("");
            this.usuario_txt.setForeground(Color.black);
        }
    }//GEN-LAST:event_usuario_txtFocusGained

    private void usuario_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuario_txtFocusLost
        
        if(this.usuario_txt.getText().isEmpty()){
            this.usuario_txt.setText("Ingrese su nombre de usuario");
            this.usuario_txt.setForeground(Color.LIGHT_GRAY);
        }
        
    }//GEN-LAST:event_usuario_txtFocusLost

    private void contrasena_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contrasena_txtFocusGained
        
        if(String.valueOf(contrasena_txt.getPassword()).equals("••••••••••••")){
            this.contrasena_txt.setText("");
            this.contrasena_txt.setForeground(Color.black);
        }
        
    }//GEN-LAST:event_contrasena_txtFocusGained

    private void contrasena_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contrasena_txtFocusLost
        
        if(String.valueOf(contrasena_txt.getPassword()).isEmpty()){
            this.contrasena_txt.setText("••••••••••••");
            this.contrasena_txt.setForeground(Color.LIGHT_GRAY);
        }
        
    }//GEN-LAST:event_contrasena_txtFocusLost

    private void mostrarcontrasena_checkboxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mostrarcontrasena_checkboxStateChanged
        
        if(this.mostrarcontrasena_checkbox.isSelected()){
            if(! String.valueOf(contrasena_txt.getPassword()).equals("••••••••")){
                this.contrasena_txt.setEchoChar((char) 0);
            }
        }
        else{
            this.contrasena_txt.setEchoChar('•');
        }
    }//GEN-LAST:event_mostrarcontrasena_checkboxStateChanged

    private void ingresar_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresar_buttonMouseClicked
        String usuario = this.usuario_txt.getText();
        String contrasena = String.valueOf(this.contrasena_txt.getPassword());
        
        if(usuario.isEmpty() || usuario.equals("Ingrese su nombre de usuario"))
            this.aviso_usuario.setText("Ingresar usuario obligatoriamente");
        else
            this.aviso_usuario.setText(" ");
        if(contrasena.isEmpty() || contrasena.equals("••••••••"))
            this.aviso_contrasena.setText("Ingresar contraseña obligatoriamente");
        else
            this.aviso_contrasena.setText(" ");
        
        
        if(!(usuario.isEmpty() || usuario.equals("Ingrese su nombre de usuario")) && !(contrasena.isEmpty() ||contrasena.equals("••••••••"))){
            
            int idEmpleado = 1;
            
            if(idEmpleado != -1){
            
                //contra de prueba: 1
                String contra ="1";
                if(contra.equals(contrasena)){
                    Menu sb_menu = new Menu();
                    sb_menu.setVisible(true);
                    this.setVisible(false);
                }
                else
                    this.aviso_contrasena.setText("Contraseña incorrecta");
            }
            else
                this.aviso_usuario.setText("No se encontro al usuario");
        }
            
            /*Controladora control = new Controladora();
            int idEmpleado = -1;
            ArrayList<Empleado> listaEmpleados = control.traerListaEmpleados();
            
            for (Empleado emp : listaEmpleados){
                if(emp.getUsuario().equals(usuario)){
                    idEmpleado = emp.getId();
                }
            }
            
            if(idEmpleado != -1){
                Empleado emp = control.traerEmpleado(idEmpleado);
            
                try {
                    if(enc.desencriptar(emp.getContraseña()).equals(contrasena)){
                        CodeBank_Menu sb_menu = new CodeBank_Menu();
                        sb_menu.setVisible(true);
                        this.setVisible(false);
                    }
                    else
                        this.avisoContraseña.setText("Contraseña incorrecta");
                } catch (Exception ex) {
                    Logger.getLogger(CodeBank_LogIn.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            else
                this.aviso_usuario.setText("No se encontro al usuario");
        }
        */
    }//GEN-LAST:event_ingresar_buttonMouseClicked

    private void ingresar_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresar_buttonMouseEntered
        SetImageLabel(ingresar_button, "imagenes/ingresar_button_click.png");
    }//GEN-LAST:event_ingresar_buttonMouseEntered

    private void ingresar_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresar_buttonMouseExited
        SetImageLabel(ingresar_button, "imagenes/ingresar_button_default.png");
    }//GEN-LAST:event_ingresar_buttonMouseExited

    private void SetImageLabel(JLabel labelName, String root) {
        URL imageURL = getClass().getClassLoader().getResource(root);
        if (imageURL != null) {
            ImageIcon image = new ImageIcon(imageURL);
            Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(
                    labelName.getWidth(),
                    labelName.getHeight(),
                    Image.SCALE_SMOOTH
                )
            );
            labelName.setIcon(icon);
            this.repaint();
        } else {
            System.err.println("No se pudo encontrar la imagen: " + root);
    }
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aviso_contrasena;
    private javax.swing.JLabel aviso_usuario;
    private javax.swing.JLabel contrasena_title;
    private javax.swing.JPasswordField contrasena_txt;
    private javax.swing.JLabel ingresar_button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel login_fondo;
    private javax.swing.JLabel login_icon;
    private javax.swing.JLabel login_title;
    private javax.swing.JCheckBox mostrarcontrasena_checkbox;
    private javax.swing.JLabel usuario_title;
    private javax.swing.JTextField usuario_txt;
    // End of variables declaration//GEN-END:variables

}
