/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sistemaestacionamiento.gui;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author USER
 */
public class CE_MostrarParqueo extends javax.swing.JPanel {

    /**
     * Creates new form CE_MostrarParqueo_1
     */
    public CE_MostrarParqueo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        piso2_button = new javax.swing.JButton();
        piso1_button = new javax.swing.JButton();
        fondo_pisos = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        piso2_button.setBackground(new java.awt.Color(204, 204, 204));
        piso2_button.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        piso2_button.setForeground(new java.awt.Color(102, 102, 102));
        piso2_button.setText("Piso 2");
        piso2_button.setBorder(null);
        piso2_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        piso2_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piso2_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(piso2_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 70, 20));

        piso1_button.setBackground(new java.awt.Color(204, 204, 204));
        piso1_button.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        piso1_button.setForeground(new java.awt.Color(102, 102, 102));
        piso1_button.setText("Piso 1");
        piso1_button.setBorder(null);
        piso1_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        piso1_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piso1_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(piso1_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 70, 20));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 610, 40));

        fondo_pisos.setBackground(new java.awt.Color(248, 248, 248));
        add(fondo_pisos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void piso1_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piso1_buttonActionPerformed
        Piso1 piso_1 = new Piso1();
        cambiarPanel(piso_1);
    }//GEN-LAST:event_piso1_buttonActionPerformed

    private void piso2_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piso2_buttonActionPerformed
        Piso2 piso_2 = new Piso2();
        cambiarPanel(piso_2);
    }//GEN-LAST:event_piso2_buttonActionPerformed

    private void cambiarPanel(JPanel p){
        
        p.setSize(this.fondo_pisos.getWidth(), this.fondo_pisos.getHeight());
        p.setLocation(0, 0);
        
        this.fondo_pisos.setLayout(new BorderLayout());
        
        this.fondo_pisos.removeAll();
        
        this.fondo_pisos.add(p, BorderLayout.CENTER);
        this.fondo_pisos.revalidate();
        this.fondo_pisos.repaint();
        
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fondo_pisos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton piso1_button;
    private javax.swing.JButton piso2_button;
    // End of variables declaration//GEN-END:variables
}
