/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sistemaestacionamiento.gui;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Jose
 */
public class ControlBusqueda extends javax.swing.JPanel {

    /**
     * Creates new form ControlBusqueda
     */
    public ControlBusqueda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        placa_button = new javax.swing.JButton();
        escenario_panel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        codigo_button = new javax.swing.JButton();
        fecha_button = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        placa_button.setBackground(new java.awt.Color(79, 79, 79));
        placa_button.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        placa_button.setForeground(new java.awt.Color(204, 204, 204));
        placa_button.setText("Placa");
        placa_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        placa_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placa_buttonActionPerformed(evt);
            }
        });
        add(placa_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 200, 40));

        escenario_panel.setBackground(new java.awt.Color(255, 255, 255));
        escenario_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(escenario_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 610, 560));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, -1));

        codigo_button.setBackground(new java.awt.Color(79, 79, 79));
        codigo_button.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        codigo_button.setForeground(new java.awt.Color(204, 204, 204));
        codigo_button.setText("Codigo");
        codigo_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        codigo_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        codigo_button.setDefaultCapable(false);
        codigo_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigo_buttonActionPerformed(evt);
            }
        });
        add(codigo_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        fecha_button.setBackground(new java.awt.Color(79, 79, 79));
        fecha_button.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        fecha_button.setForeground(new java.awt.Color(204, 204, 204));
        fecha_button.setText("Fecha");
        fecha_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fecha_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecha_buttonActionPerformed(evt);
            }
        });
        add(fecha_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 210, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void placa_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placa_buttonActionPerformed
        placaBusqueda placa = new placaBusqueda();
        cambiarPanel (placa);
    }//GEN-LAST:event_placa_buttonActionPerformed

    private void codigo_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigo_buttonActionPerformed
         codigoBusqueda cod = new codigoBusqueda();
        cambiarPanel (cod);
    }//GEN-LAST:event_codigo_buttonActionPerformed

    private void fecha_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecha_buttonActionPerformed
        fechaBusqueda fech = new fechaBusqueda();
        cambiarPanel (fech);
    }//GEN-LAST:event_fecha_buttonActionPerformed
    
    public void cambiarPanel(JPanel p){
        
        p.setSize(this.escenario_panel.getWidth(), this.escenario_panel.getHeight());
        p.setLocation(0, 0);
        
        this.escenario_panel.setLayout(new BorderLayout());
        
        this.escenario_panel.removeAll();
        
        this.escenario_panel.add(p, BorderLayout.CENTER);
        this.escenario_panel.revalidate();
        this.escenario_panel.repaint();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton codigo_button;
    private javax.swing.JPanel escenario_panel;
    private javax.swing.JButton fecha_button;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton placa_button;
    // End of variables declaration//GEN-END:variables
}
