/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemaestacionamiento.gui;

import javax.swing.*;
import java.awt.*;
import java.net.URL;

/**
 *
 * @author USER
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        SetImageLabel(controlestacionamiento_button1, "imagenes/controlestacionamiento_button_default.png");
        SetImageLabel(gestionusuarios_button, "imagenes/administrarusuarios_button_default.png");
        SetImageLabel(cerrarsesion_button, "imagenes/cerrarsesion_button_default.png");
        //SetImageLabel(menu_background, "imagenes/menu_image.png");
        /*
        //Imagen para barra
        // 1. Crear el nuevo panel con imagen de fondo
        FondoPanel fondo = new FondoPanel("imagenes/menu_image.png");

        // 2. Ajustar su tamaño y layout igual al panel original
        fondo.setBounds(menu.getBounds());
        fondo.setLayout(menu.getLayout());

        // 3. Pasar los componentes del panel original al nuevo
        Component[] componentes = menu.getComponents();
        for (Component comp : componentes) {
            menu.remove(comp);
            fondo.add(comp);
        }

        // 4. Reemplazar el panel `menu` en el JFrame
        this.remove(menu);
        this.add(fondo);

        // 5. Forzar actualización de la interfaz
        this.revalidate();
        this.repaint();
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_menu = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        controlestacionamiento_button1 = new javax.swing.JLabel();
        gestionusuarios_button = new javax.swing.JLabel();
        cerrarsesion_button = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Estacionamiento");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_menu.setBackground(new java.awt.Color(255, 255, 255));
        panel_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(panel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 570, 460));

        menu.setBackground(new java.awt.Color(255, 255, 255));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        controlestacionamiento_button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                controlestacionamiento_button1MouseClicked(evt);
            }
        });
        menu.add(controlestacionamiento_button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 140, 40));

        gestionusuarios_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gestionusuarios_buttonMouseClicked(evt);
            }
        });
        menu.add(gestionusuarios_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 140, 40));
        menu.add(cerrarsesion_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 140, 40));

        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void controlestacionamiento_button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_controlestacionamiento_button1MouseClicked
        // TODO add your handling code here:
        ControlEstacionamiento ctrest = new ControlEstacionamiento();
        cambiarPanel(ctrest);
    }//GEN-LAST:event_controlestacionamiento_button1MouseClicked

    private void gestionusuarios_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestionusuarios_buttonMouseClicked
        // TODO add your handling code here:
        AdminUser ctres = new AdminUser();
        cambiarPanel(ctres);
    }//GEN-LAST:event_gestionusuarios_buttonMouseClicked
    
    private void cambiarPanel(JPanel p){
        
        p.setSize(this.panel_menu.getWidth(), this.panel_menu.getHeight());
        p.setLocation(0, 0);
        
        this.panel_menu.setLayout(new BorderLayout());
        
        this.panel_menu.removeAll();
        
        this.panel_menu.add(p, BorderLayout.CENTER);
        this.panel_menu.revalidate();
        this.panel_menu.repaint();
        
    }
    
    private void SetImageLabel(JLabel labelName, String root) {
        URL imageURL = getClass().getClassLoader().getResource(root);
        if (imageURL != null) {
            ImageIcon image = new ImageIcon(imageURL);
            Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(
                    labelName.getWidth(),
                    labelName.getHeight(),
                    Image.SCALE_SMOOTH
                )
            );
            labelName.setIcon(icon);
            this.repaint();
        } else {
            System.err.println("No se pudo encontrar la imagen: " + root);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cerrarsesion_button;
    private javax.swing.JLabel controlestacionamiento_button1;
    private javax.swing.JLabel gestionusuarios_button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel panel_menu;
    // End of variables declaration//GEN-END:variables

    /*class FondoPanel extends JPanel {

        private Image imagen;

        public FondoPanel(String rutaImagen) {
            URL imageUrl = getClass().getClassLoader().getResource(rutaImagen);
            if (imageUrl != null) {
                this.imagen = new ImageIcon(imageUrl).getImage();
            } else {
                System.err.println("️No se encontró la imagen: " + rutaImagen);
            }
        }

        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            System.out.println("Pintando el fondo del panel...");

            if (imagen != null) {
                g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            }
        }
    }*/


}
