/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sistemaestacionamiento.gui;

/**
 *
 * @author Jose
 */
public class Piso2 extends javax.swing.JPanel {

    /**
     * Creates new form Piso2
     */
    public Piso2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B2 = new javax.swing.JPanel();
        B2text = new javax.swing.JLabel();
        B1 = new javax.swing.JPanel();
        B1text = new javax.swing.JLabel();
        B5 = new javax.swing.JPanel();
        B5text = new javax.swing.JLabel();
        rampa = new javax.swing.JPanel();
        rampTxt = new javax.swing.JLabel();
        B3 = new javax.swing.JPanel();
        B3text = new javax.swing.JLabel();
        B4 = new javax.swing.JPanel();
        B4text = new javax.swing.JLabel();
        B6 = new javax.swing.JPanel();
        B6text = new javax.swing.JLabel();
        B8 = new javax.swing.JPanel();
        B8text = new javax.swing.JLabel();
        B9 = new javax.swing.JPanel();
        B9text = new javax.swing.JLabel();
        B7 = new javax.swing.JPanel();
        B7text = new javax.swing.JLabel();
        B10 = new javax.swing.JPanel();
        B10text = new javax.swing.JLabel();
        B11 = new javax.swing.JPanel();
        B11text = new javax.swing.JLabel();
        B12 = new javax.swing.JPanel();
        B12text = new javax.swing.JLabel();
        B13 = new javax.swing.JPanel();
        B13text = new javax.swing.JLabel();
        B14 = new javax.swing.JPanel();
        B14text = new javax.swing.JLabel();
        B15 = new javax.swing.JPanel();
        B15text = new javax.swing.JLabel();
        B16 = new javax.swing.JPanel();
        B16text = new javax.swing.JLabel();
        B17 = new javax.swing.JPanel();
        B17text = new javax.swing.JLabel();
        B18 = new javax.swing.JPanel();
        B18text = new javax.swing.JLabel();
        B19 = new javax.swing.JPanel();
        B19text = new javax.swing.JLabel();
        B20 = new javax.swing.JPanel();
        B20text = new javax.swing.JLabel();
        B21 = new javax.swing.JPanel();
        B21text = new javax.swing.JLabel();
        B22 = new javax.swing.JPanel();
        B22text = new javax.swing.JLabel();

        B2.setBackground(new java.awt.Color(255, 0, 0));
        B2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B2.setForeground(new java.awt.Color(255, 255, 255));
        B2.setPreferredSize(new java.awt.Dimension(65, 41));

        B2text.setBackground(new java.awt.Color(255, 51, 0));
        B2text.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        B2text.setForeground(new java.awt.Color(255, 255, 255));
        B2text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B2text.setText("B2");

        javax.swing.GroupLayout B2Layout = new javax.swing.GroupLayout(B2);
        B2.setLayout(B2Layout);
        B2Layout.setHorizontalGroup(
            B2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B2text, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        B2Layout.setVerticalGroup(
            B2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B2text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        B1.setBackground(new java.awt.Color(0, 102, 51));
        B1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B1.setForeground(new java.awt.Color(140, 150, 200));

        B1text.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        B1text.setForeground(new java.awt.Color(255, 255, 255));
        B1text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B1text.setText("B1");

        javax.swing.GroupLayout B1Layout = new javax.swing.GroupLayout(B1);
        B1.setLayout(B1Layout);
        B1Layout.setHorizontalGroup(
            B1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B1text, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        B1Layout.setVerticalGroup(
            B1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B1text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        B5.setBackground(new java.awt.Color(0, 102, 51));
        B5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B5.setForeground(new java.awt.Color(140, 150, 200));

        B5text.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        B5text.setForeground(new java.awt.Color(255, 255, 255));
        B5text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B5text.setText("B5");

        javax.swing.GroupLayout B5Layout = new javax.swing.GroupLayout(B5);
        B5.setLayout(B5Layout);
        B5Layout.setHorizontalGroup(
            B5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B5text, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        B5Layout.setVerticalGroup(
            B5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B5text, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        rampa.setBackground(new java.awt.Color(58, 65, 133));
        rampa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rampa.setForeground(new java.awt.Color(31, 39, 115));

        rampTxt.setBackground(new java.awt.Color(0, 102, 204));
        rampTxt.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        rampTxt.setForeground(new java.awt.Color(255, 255, 255));
        rampTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rampTxt.setText("RAMPA ENTRE PISO 1 Y 2");

        javax.swing.GroupLayout rampaLayout = new javax.swing.GroupLayout(rampa);
        rampa.setLayout(rampaLayout);
        rampaLayout.setHorizontalGroup(
            rampaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rampaLayout.createSequentialGroup()
                .addComponent(rampTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
        );
        rampaLayout.setVerticalGroup(
            rampaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rampaLayout.createSequentialGroup()
                .addComponent(rampTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );

        B3.setBackground(new java.awt.Color(0, 102, 51));
        B3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B3.setForeground(new java.awt.Color(140, 150, 200));

        B3text.setBackground(new java.awt.Color(0, 102, 51));
        B3text.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        B3text.setForeground(new java.awt.Color(255, 255, 255));
        B3text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B3text.setText("B3");

        javax.swing.GroupLayout B3Layout = new javax.swing.GroupLayout(B3);
        B3.setLayout(B3Layout);
        B3Layout.setHorizontalGroup(
            B3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B3text, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        B3Layout.setVerticalGroup(
            B3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B3text, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        B4.setBackground(new java.awt.Color(0, 102, 51));
        B4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B4.setForeground(new java.awt.Color(140, 150, 200));

        B4text.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        B4text.setForeground(new java.awt.Color(255, 255, 255));
        B4text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B4text.setText("B4");

        javax.swing.GroupLayout B4Layout = new javax.swing.GroupLayout(B4);
        B4.setLayout(B4Layout);
        B4Layout.setHorizontalGroup(
            B4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B4text, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        B4Layout.setVerticalGroup(
            B4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B4text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        B6.setBackground(new java.awt.Color(0, 102, 51));
        B6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B6.setForeground(new java.awt.Color(140, 150, 200));

        B6text.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        B6text.setForeground(new java.awt.Color(255, 255, 255));
        B6text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B6text.setText("B6");

        javax.swing.GroupLayout B6Layout = new javax.swing.GroupLayout(B6);
        B6.setLayout(B6Layout);
        B6Layout.setHorizontalGroup(
            B6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B6text, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        B6Layout.setVerticalGroup(
            B6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B6text, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        B8.setBackground(new java.awt.Color(0, 107, 51));
        B8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B8.setForeground(new java.awt.Color(140, 150, 200));

        B8text.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        B8text.setForeground(new java.awt.Color(255, 255, 255));
        B8text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B8text.setText("B7");

        javax.swing.GroupLayout B8Layout = new javax.swing.GroupLayout(B8);
        B8.setLayout(B8Layout);
        B8Layout.setHorizontalGroup(
            B8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B8text, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        B8Layout.setVerticalGroup(
            B8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B8text, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        B9.setBackground(new java.awt.Color(0, 107, 51));
        B9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B9.setForeground(new java.awt.Color(140, 150, 200));

        B9text.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        B9text.setForeground(new java.awt.Color(255, 255, 255));
        B9text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B9text.setText("B9");

        javax.swing.GroupLayout B9Layout = new javax.swing.GroupLayout(B9);
        B9.setLayout(B9Layout);
        B9Layout.setHorizontalGroup(
            B9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B9text, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        B9Layout.setVerticalGroup(
            B9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B9text, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        B7.setBackground(new java.awt.Color(0, 107, 51));
        B7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B7.setForeground(new java.awt.Color(140, 150, 200));

        B7text.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        B7text.setForeground(new java.awt.Color(255, 255, 255));
        B7text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B7text.setText("B7");

        javax.swing.GroupLayout B7Layout = new javax.swing.GroupLayout(B7);
        B7.setLayout(B7Layout);
        B7Layout.setHorizontalGroup(
            B7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B7text, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        B7Layout.setVerticalGroup(
            B7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B7text, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        B10.setBackground(new java.awt.Color(0, 107, 51));
        B10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B10.setForeground(new java.awt.Color(140, 150, 200));

        B10text.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        B10text.setForeground(new java.awt.Color(255, 255, 255));
        B10text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B10text.setText("B10");

        javax.swing.GroupLayout B10Layout = new javax.swing.GroupLayout(B10);
        B10.setLayout(B10Layout);
        B10Layout.setHorizontalGroup(
            B10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B10text, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        B10Layout.setVerticalGroup(
            B10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B10text, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        B11.setBackground(new java.awt.Color(0, 107, 51));
        B11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B11.setForeground(new java.awt.Color(140, 150, 200));

        B11text.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        B11text.setForeground(new java.awt.Color(255, 255, 255));
        B11text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B11text.setText("B11");

        javax.swing.GroupLayout B11Layout = new javax.swing.GroupLayout(B11);
        B11.setLayout(B11Layout);
        B11Layout.setHorizontalGroup(
            B11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B11text, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        B11Layout.setVerticalGroup(
            B11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B11text, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        B12.setBackground(new java.awt.Color(0, 107, 51));
        B12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B12.setForeground(new java.awt.Color(140, 150, 200));

        B12text.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        B12text.setForeground(new java.awt.Color(255, 255, 255));
        B12text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B12text.setText("B12");

        javax.swing.GroupLayout B12Layout = new javax.swing.GroupLayout(B12);
        B12.setLayout(B12Layout);
        B12Layout.setHorizontalGroup(
            B12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B12text, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        B12Layout.setVerticalGroup(
            B12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B12text, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        B13.setBackground(new java.awt.Color(0, 107, 51));
        B13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B13.setForeground(new java.awt.Color(140, 150, 200));

        B13text.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        B13text.setForeground(new java.awt.Color(255, 255, 255));
        B13text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B13text.setText("B13");

        javax.swing.GroupLayout B13Layout = new javax.swing.GroupLayout(B13);
        B13.setLayout(B13Layout);
        B13Layout.setHorizontalGroup(
            B13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B13text, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        B13Layout.setVerticalGroup(
            B13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B13text, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        B14.setBackground(new java.awt.Color(0, 107, 51));
        B14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B14.setForeground(new java.awt.Color(140, 150, 200));

        B14text.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        B14text.setForeground(new java.awt.Color(255, 255, 255));
        B14text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B14text.setText("B14");

        javax.swing.GroupLayout B14Layout = new javax.swing.GroupLayout(B14);
        B14.setLayout(B14Layout);
        B14Layout.setHorizontalGroup(
            B14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B14text, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        B14Layout.setVerticalGroup(
            B14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B14text, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        B15.setBackground(new java.awt.Color(0, 107, 51));
        B15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B15.setForeground(new java.awt.Color(140, 150, 200));

        B15text.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        B15text.setForeground(new java.awt.Color(255, 255, 255));
        B15text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B15text.setText("B15");

        javax.swing.GroupLayout B15Layout = new javax.swing.GroupLayout(B15);
        B15.setLayout(B15Layout);
        B15Layout.setHorizontalGroup(
            B15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B15text, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        B15Layout.setVerticalGroup(
            B15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B15text, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        B16.setBackground(new java.awt.Color(0, 107, 51));
        B16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B16.setForeground(new java.awt.Color(140, 150, 200));

        B16text.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        B16text.setForeground(new java.awt.Color(255, 255, 255));
        B16text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B16text.setText("B16");

        javax.swing.GroupLayout B16Layout = new javax.swing.GroupLayout(B16);
        B16.setLayout(B16Layout);
        B16Layout.setHorizontalGroup(
            B16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B16text, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        B16Layout.setVerticalGroup(
            B16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B16text, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        B17.setBackground(new java.awt.Color(0, 107, 51));
        B17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B17.setForeground(new java.awt.Color(140, 150, 200));

        B17text.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        B17text.setForeground(new java.awt.Color(255, 255, 255));
        B17text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B17text.setText("B17");

        javax.swing.GroupLayout B17Layout = new javax.swing.GroupLayout(B17);
        B17.setLayout(B17Layout);
        B17Layout.setHorizontalGroup(
            B17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B17text, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        B17Layout.setVerticalGroup(
            B17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B17text, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        B18.setBackground(new java.awt.Color(0, 107, 51));
        B18.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B18.setForeground(new java.awt.Color(140, 150, 200));

        B18text.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        B18text.setForeground(new java.awt.Color(255, 255, 255));
        B18text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B18text.setText("B18");

        javax.swing.GroupLayout B18Layout = new javax.swing.GroupLayout(B18);
        B18.setLayout(B18Layout);
        B18Layout.setHorizontalGroup(
            B18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B18text, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        B18Layout.setVerticalGroup(
            B18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B18text, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        B19.setBackground(new java.awt.Color(0, 107, 51));
        B19.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B19.setForeground(new java.awt.Color(140, 150, 200));

        B19text.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        B19text.setForeground(new java.awt.Color(255, 255, 255));
        B19text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B19text.setText("B19");

        javax.swing.GroupLayout B19Layout = new javax.swing.GroupLayout(B19);
        B19.setLayout(B19Layout);
        B19Layout.setHorizontalGroup(
            B19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B19text, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        B19Layout.setVerticalGroup(
            B19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B19text, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        B20.setBackground(new java.awt.Color(0, 107, 51));
        B20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B20.setForeground(new java.awt.Color(140, 150, 200));

        B20text.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        B20text.setForeground(new java.awt.Color(255, 255, 255));
        B20text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B20text.setText("B20");

        javax.swing.GroupLayout B20Layout = new javax.swing.GroupLayout(B20);
        B20.setLayout(B20Layout);
        B20Layout.setHorizontalGroup(
            B20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B20text, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        B20Layout.setVerticalGroup(
            B20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B20text, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        B21.setBackground(new java.awt.Color(0, 107, 51));
        B21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B21.setForeground(new java.awt.Color(140, 150, 200));

        B21text.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        B21text.setForeground(new java.awt.Color(255, 255, 255));
        B21text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B21text.setText("B21");

        javax.swing.GroupLayout B21Layout = new javax.swing.GroupLayout(B21);
        B21.setLayout(B21Layout);
        B21Layout.setHorizontalGroup(
            B21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B21text, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        B21Layout.setVerticalGroup(
            B21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B21text, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        B22.setBackground(new java.awt.Color(0, 107, 51));
        B22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B22.setForeground(new java.awt.Color(140, 150, 200));

        B22text.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        B22text.setForeground(new java.awt.Color(255, 255, 255));
        B22text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B22text.setText("B22");

        javax.swing.GroupLayout B22Layout = new javax.swing.GroupLayout(B22);
        B22.setLayout(B22Layout);
        B22Layout.setHorizontalGroup(
            B22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B22text, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );
        B22Layout.setVerticalGroup(
            B22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(B22text, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 9, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(B10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(B11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(B12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(B13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(B14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(B15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(B16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(B17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(B18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(B19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(B21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(B20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(B22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(32, 32, 32)
                            .addComponent(rampa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 10, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 7, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(27, 27, 27)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(27, 27, 27)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(B13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(27, 27, 27)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(B19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(B21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(B20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(B22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(rampa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 7, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel B1;
    private javax.swing.JPanel B10;
    private javax.swing.JLabel B10text;
    private javax.swing.JPanel B11;
    private javax.swing.JLabel B11text;
    private javax.swing.JPanel B12;
    private javax.swing.JLabel B12text;
    private javax.swing.JPanel B13;
    private javax.swing.JLabel B13text;
    private javax.swing.JPanel B14;
    private javax.swing.JLabel B14text;
    private javax.swing.JPanel B15;
    private javax.swing.JLabel B15text;
    private javax.swing.JPanel B16;
    private javax.swing.JLabel B16text;
    private javax.swing.JPanel B17;
    private javax.swing.JLabel B17text;
    private javax.swing.JPanel B18;
    private javax.swing.JLabel B18text;
    private javax.swing.JPanel B19;
    private javax.swing.JLabel B19text;
    private javax.swing.JLabel B1text;
    private javax.swing.JPanel B2;
    private javax.swing.JPanel B20;
    private javax.swing.JLabel B20text;
    private javax.swing.JPanel B21;
    private javax.swing.JLabel B21text;
    private javax.swing.JPanel B22;
    private javax.swing.JLabel B22text;
    private javax.swing.JLabel B2text;
    private javax.swing.JPanel B3;
    private javax.swing.JLabel B3text;
    private javax.swing.JPanel B4;
    private javax.swing.JLabel B4text;
    private javax.swing.JPanel B5;
    private javax.swing.JLabel B5text;
    private javax.swing.JPanel B6;
    private javax.swing.JLabel B6text;
    private javax.swing.JPanel B7;
    private javax.swing.JLabel B7text;
    private javax.swing.JPanel B8;
    private javax.swing.JLabel B8text;
    private javax.swing.JPanel B9;
    private javax.swing.JLabel B9text;
    private javax.swing.JLabel rampTxt;
    private javax.swing.JPanel rampa;
    // End of variables declaration//GEN-END:variables
}
